"""add part_sector and measurement_parameters

Revision ID: 39f73466e504
Revises: a2796e0adacc
Create Date: 2026-07-06 18:35:44.512086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f73466e504'
down_revision: Union[str, Sequence[str], None] = 'a2796e0adacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('part_sector', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('measurement_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'measurement_parameters')
    op.drop_column('parts', 'part_sector')
    # ### end Alembic commands ###
