"""initial schema

Revision ID: a2796e0adacc
Revises: 
Create Date: 2026-07-03 16:56:47.196047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2796e0adacc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('defects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_sessions_part_id'), table_name='company_sessions')
    op.drop_index(op.f('ix_sessions_session_start'), table_name='company_sessions')
    op.create_index(op.f('ix_company_sessions_part_id'), 'company_sessions', ['part_id'], unique=False)
    op.create_index(op.f('ix_company_sessions_session_start'), 'company_sessions', ['session_start'], unique=False)
    op.add_column('part_defects', sa.Column('defects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('part_defects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('part_defects', 'scratch')
    op.drop_column('part_defects', 'thread_missing')
    op.drop_column('part_defects', 'rust')
    op.drop_column('part_defects', 'dent')
    op.drop_constraint(op.f('parts_part_code_key'), 'parts', type_='unique')
    op.drop_index(op.f('ix_parts_part_code'), table_name='parts')
    op.create_index(op.f('ix_parts_part_code'), 'parts', ['part_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_part_code'), table_name='parts')
    op.create_index(op.f('ix_parts_part_code'), 'parts', ['part_code'], unique=False)
    op.create_unique_constraint(op.f('parts_part_code_key'), 'parts', ['part_code'], postgresql_nulls_not_distinct=False)
    op.add_column('part_defects', sa.Column('dent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('part_defects', sa.Column('rust', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('part_defects', sa.Column('thread_missing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('part_defects', sa.Column('scratch', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('part_defects', 'created_at')
    op.drop_column('part_defects', 'defects')
    op.drop_index(op.f('ix_company_sessions_session_start'), table_name='company_sessions')
    op.drop_index(op.f('ix_company_sessions_part_id'), table_name='company_sessions')
    op.create_index(op.f('ix_sessions_session_start'), 'company_sessions', ['session_start'], unique=False)
    op.create_index(op.f('ix_sessions_part_id'), 'company_sessions', ['part_id'], unique=False)
    op.drop_column('ai_models', 'defects')
    # ### end Alembic commands ###
