"""drop ai_models and consolidate part dimensions

Revision ID: c2d685ff1b3d
Revises: 39f73466e504
Create Date: 2026-07-23 17:59:08.116882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d685ff1b3d'
down_revision: Union[str, Sequence[str], None] = '39f73466e504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # drop the FK/index/column on parts FIRST
    op.drop_constraint('parts_ai_model_id_fkey', 'parts', type_='foreignkey')
    op.drop_index('ix_parts_ai_model_id', table_name='parts')
    op.drop_column('parts', 'ai_model_id')

    # now safe to drop ai_models entirely
    op.drop_index('ix_ai_models_model_id', table_name='ai_models')
    op.drop_table('ai_models')

    # the 8 dimension columns
    op.drop_column('parts', 'part_sector')
    op.drop_column('parts', 'actual_measurement_data')
    op.drop_column('parts', 'part_outer_diameter')
    op.drop_column('parts', 'part_width')
    op.drop_column('parts', 'part_inner_diameter')
    op.drop_column('parts', 'part_arch_length')
    op.drop_column('parts', 'part_height')
    op.drop_column('parts', 'part_angle')
    op.drop_column('parts', 'part_length')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('ai_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_angle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_arch_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_inner_diameter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_outer_diameter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('actual_measurement_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_sector', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('parts_ai_model_id_fkey'), 'parts', 'ai_models', ['ai_model_id'], ['model_id'], ondelete='SET NULL')
    op.create_index(op.f('ix_parts_ai_model_id'), 'parts', ['ai_model_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('model_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('defects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('model_id', name=op.f('ai_models_pkey')),
    sa.UniqueConstraint('model_name', name=op.f('ai_models_model_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ai_models_model_id'), 'ai_models', ['model_id'], unique=False)
    # ### end Alembic commands ###
