-- =====================================================================
-- Migration 001: add AI models
--
-- Adds the `ai_models` table and links `parts` to it via `parts.ai_model_id`.
-- Safe to run on an existing, populated database (idempotent).
--
--   psql "$DATABASE_URL" -f migrations/001_add_ai_models.sql
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS ai_models (
    model_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name     TEXT NOT NULL UNIQUE,
    model_type     TEXT,
    model_path     TEXT,
    description    TEXT,
    model_metadata JSONB,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP DEFAULT now()
);

ALTER TABLE parts
    ADD COLUMN IF NOT EXISTS ai_model_id INTEGER
    REFERENCES ai_models(model_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_parts_ai_model_id  ON parts (ai_model_id);
CREATE INDEX IF NOT EXISTS ix_ai_models_model_id ON ai_models (model_id);

COMMIT;
