-- =====================================================================
-- MV Desktop  ->  PostgreSQL schema  (consolidated / collapsed)
--
-- Equivalent to the full SQLite migration chain, collapsed into one file:
--   v001 initial  -> v002 part_defects -> v004 mode_of_operation
--   -> v005 restructure parts (inner/outer dia, measurements, flags)
--   -> v006 clean company_sessions (measured_realtime_data, overall_status)
--   -> v007 fix part_defects
--   + ai_models (NEW: AI model registry) and parts.ai_model_id (NEW link)
--
-- Translation (SQLite -> PostgreSQL):
--   INTEGER PK AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   JSON-in-TEXT             -> JSONB
--   BLOB                     -> BYTEA
--   0/1 flags                -> BOOLEAN
--   REAL                     -> DOUBLE PRECISION
--   CHECK(... IN ...)        -> kept
--   CURRENT_TIMESTAMP        -> now()   (TIMESTAMPTZ)
--
-- Run once:  psql "$DATABASE_URL" -f schema.sql
-- =====================================================================

BEGIN;

-- ── categories ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE
);

-- ── users ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL
                  CHECK (role IN ('operator', 'administrator', 'superadministrator'))
);

-- ── ai_models  (NEW) ─────────────────────────────────────────────────
--   The "Add new AI model" button creates rows here.
--   model_name  = the linking name used by the backend (e.g. 'bolt')
--   model_path  = the weights file in the backend        (e.g. 'bolt.pt')
CREATE TABLE IF NOT EXISTS ai_models (
    model_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name     TEXT NOT NULL UNIQUE,
    model_path     TEXT,
    model_type     TEXT,
    description    TEXT,
    model_metadata JSONB,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ DEFAULT now()
);

-- ── parts  (final structure, v005) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS parts (
    part_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code           TEXT NOT NULL UNIQUE,
    part_name           TEXT NOT NULL,

    category_id         INTEGER REFERENCES categories(category_id) ON DELETE SET NULL,
    -- NEW: link a part to its AI model (set on the add-item page or Excel import)
    ai_model_id         INTEGER REFERENCES ai_models(model_id) ON DELETE SET NULL,

    parts_metadata      TEXT,
    created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ DEFAULT now(),
    image               BYTEA,

    -- basic dimensions
    part_weight         DOUBLE PRECISION,
    part_height         DOUBLE PRECISION,
    part_width          DOUBLE PRECISION,

    -- diameter structure (v005)
    part_inner_diameter DOUBLE PRECISION,
    part_outer_diameter DOUBLE PRECISION,

    -- master measurement config (JSON)
    actual_measurement_data JSONB,

    -- additional measurements
    part_length         DOUBLE PRECISION,
    part_angle          DOUBLE PRECISION,
    part_arch_length    DOUBLE PRECISION,

    -- boolean flags
    part_co_planarity   BOOLEAN NOT NULL DEFAULT FALSE,
    part_parallelity    BOOLEAN NOT NULL DEFAULT FALSE,
    part_concentricity  BOOLEAN NOT NULL DEFAULT FALSE,

    -- mode of operation (enum)
    mode_of_operation   TEXT NOT NULL DEFAULT 'Counting'
                        CHECK (mode_of_operation IN ('Counting', 'Defect Detection', 'Measurement'))
);

-- ── company_sessions  (final structure, v006) ────────────────────────
CREATE TABLE IF NOT EXISTS company_sessions (
    id                           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id                      INTEGER REFERENCES parts(part_id) ON DELETE SET NULL,
    part_code                    TEXT NOT NULL,
    part_name                    TEXT NOT NULL,

    part_count                   INTEGER NOT NULL DEFAULT 0,
    parts_per_minute             INTEGER,

    session_start                TIMESTAMPTZ DEFAULT now(),
    session_end                  TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ DEFAULT now(),

    notes                        TEXT,
    session_weight               DOUBLE PRECISION,
    order_no                     TEXT,

    -- measurement system (JSON, detailed per parameter)
    measured_realtime_data       JSONB,

    -- overall status (fast UI + filtering)
    overall_status               TEXT CHECK (overall_status IN ('OK', 'NOK')),

    -- calibration
    is_calibration               BOOLEAN NOT NULL DEFAULT FALSE,
    calibration_expected_per_run INTEGER,
    calibration_total_runs       INTEGER,
    calibration_runs             JSONB,
    calibration_avg_count        DOUBLE PRECISION,
    calibration_avg_accuracy     DOUBLE PRECISION,
    calibration_passed           BOOLEAN,
    calibration_completed_at     TIMESTAMPTZ
);

-- ── part_defects  (final structure, v007) ────────────────────────────
CREATE TABLE IF NOT EXISTS part_defects (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     INTEGER NOT NULL REFERENCES company_sessions(id) ON DELETE CASCADE,
    part_id        INTEGER NOT NULL REFERENCES parts(part_id) ON DELETE CASCADE,
    thread_missing BOOLEAN NOT NULL DEFAULT FALSE,
    dent           BOOLEAN NOT NULL DEFAULT FALSE,
    scratch        BOOLEAN NOT NULL DEFAULT FALSE,
    rust           BOOLEAN NOT NULL DEFAULT FALSE
);

-- ── indexes ──────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS ix_categories_category_id ON categories (category_id);
CREATE INDEX IF NOT EXISTS ix_users_id               ON users (id);
CREATE INDEX IF NOT EXISTS ix_ai_models_model_id     ON ai_models (model_id);
CREATE INDEX IF NOT EXISTS ix_parts_part_id          ON parts (part_id);
CREATE INDEX IF NOT EXISTS ix_parts_part_code        ON parts (part_code);
CREATE INDEX IF NOT EXISTS ix_parts_ai_model_id      ON parts (ai_model_id);
CREATE INDEX IF NOT EXISTS ix_company_sessions_id    ON company_sessions (id);
CREATE INDEX IF NOT EXISTS ix_sessions_part_id       ON company_sessions (part_id);
CREATE INDEX IF NOT EXISTS ix_sessions_session_start ON company_sessions (session_start);
CREATE INDEX IF NOT EXISTS ix_part_defects_session_id ON part_defects (session_id);
CREATE INDEX IF NOT EXISTS ix_part_defects_part_id    ON part_defects (part_id);

-- ── seed users (migration de2fd9091667) ──────────────────────────────
-- seed the two POC users
--   admin    / admin123      (role: administrator — full access)
--   operator / operator123   (role: operator — limited access)
INSERT INTO users (id, name, username, password_hash, role) VALUES
    (1, 'Administrator', 'admin',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'administrator'),
    (2, 'Operator', 'operator',
        'ec6e1c25258002eb1c67d15c7f45da7945fa4c58778fd7d88faa5e53e3b4698d', 'operator')
ON CONFLICT (id) DO NOTHING;

-- keep the identity sequence ahead of the seeded ids
SELECT setval(pg_get_serial_sequence('users', 'id'),
              GREATEST((SELECT COALESCE(MAX(id), 1) FROM users), 1), true);

COMMIT;
